language: node_js

os:
  - osx

node_js:
  - node

install:
  - npm install

cache:
  directories:
    - "node_modules"

script:
  - npm run vscode:prepublish
  - npm test
  - npm run lint

notifications:
  email: false
